## 5. Reshaping and Transposing Arrays

### Reshaping Arrays for Analysis

Reshaping is an important operation in data analysis as it allows you to reorganize data in a way that is suitable for analysis.

![Illsutration of reshaping of numpy arrays](https://drive.google.com/uc?id=1QaQslClsGIIAXxZTDogxctKUkXF-uDXw)



In [2]:
import numpy as np

# Creating a 1D array
array = np.arange(1, 10)  # Array of numbers from 1 to 9

# Reshaping to a 3x3 matrix
reshaped_array = array.reshape(3, 3)
print("Reshaped to 3x3:\n", reshaped_array)

Reshaped to 3x3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]




### Transposing for Data Rearrangement

Transposing is another useful operation in NumPy which changes the rows into columns and vice versa, which can be crucial for certain data operations.

![Transposing matrix](https://drive.google.com/uc?id=17WuxSg9_cbRLRAjQliHdoFkX1zVA7hs3)


In [ ]:
# Transposing the reshaped array
transposed_array = reshaped_array.T
print("Transposed array:\n", transposed_array)


## Exercise: Reshaping and Transposing Arrays

1. **Reshape Array**: Create a 1D array with 12 elements and reshape it to a 4x3 matrix. Then reshape it to a 2x6 matrix.
2. **Transpose Matrix**: Transpose the 2x6 matrix you created in the previous step.
3. **Combine Reshaping and Transposing**: Create a 3x4 matrix, with numbers 1-12, transpose it, and then reshape the transposed matrix to a 1D array. Reshape the original array to a 1D array and compare the outputs.

---
### In-depth Topic: Importance of Reshaping and Transposing

1. **Data Compatibility**: Many data analysis libraries and functions expect data in a specific shape. Reshaping ensures compatibility and prevents errors. For instance, a machine learning model might require input data as a 2D array, where each row is a sample and each column is a feature.

   **Example**:
   

In [3]:
# Reshaping data for machine learning model
data = np.arange(1, 101).reshape(20, 5)  # 20 samples, 5 features each



2. **Data Visualization**: Certain types of visualizations require data in a specific format. Reshaping and transposing can be crucial for accurately representing data in visual form.

Data Visualization with Heatmaps:
When creating heatmaps, the shape of the data matrix can significantly affect the visual output. Reshaping allows for different visual interpretations of the same data.

   **Example**:
   

In [4]:
# Preparing data for heatmap visualization
matrix = np.random.rand(10, 10)
reshaped_matrix = matrix.reshape(5, 20)  # Reshaping for a different visual representation



3. **Mathematical Operations**: In linear algebra, operations like matrix multiplication require specific array shapes. Transposing arrays can make such operations feasible.

   **Example**:
   

In [5]:
# Transposing for matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([5, 6])
product = A.dot(B.transpose())  # Transposing B to make multiplication possible



### Impact on Statistical Computations

1. **Aggregation**: Reshaping can group data in ways that make aggregation operations (like sum, mean, etc.) more meaningful and aligned with the analysis goals.

   **Example**:
   

In [6]:
# Aggregating data after reshaping
data = np.random.rand(6, 2)
reshaped_data = data.reshape(3, 4)
mean_values = np.mean(reshaped_data, axis=1)  # Mean of each reshaped group

Meaningful Aggregation:
Reshaping can group data in ways that allow for more meaningful aggregation, aligning with specific analytical objectives.

In [7]:
# Aggregating data in groups after reshaping
data = np.random.rand(8, 2)  # 8 pairs of data points
reshaped_data = data.reshape(4, 4)  # Reshape to 4 groups of 4 data points
group_means = np.mean(reshaped_data, axis=1)  # Calculate mean of each group
# This reshaping groups data for more meaningful statistical aggregation
print(data, reshaped_data, group_means)

[[5.61422340e-01 1.07500276e-01]
 [6.02963617e-01 5.52071204e-01]
 [4.96738872e-01 3.72941404e-01]
 [8.80797458e-02 3.77236142e-03]
 [6.37864019e-01 3.55192567e-01]
 [5.09390102e-04 4.24153273e-01]
 [6.12734131e-01 8.03785843e-02]
 [9.05111687e-01 5.84313704e-01]] [[5.61422340e-01 1.07500276e-01 6.02963617e-01 5.52071204e-01]
 [4.96738872e-01 3.72941404e-01 8.80797458e-02 3.77236142e-03]
 [6.37864019e-01 3.55192567e-01 5.09390102e-04 4.24153273e-01]
 [6.12734131e-01 8.03785843e-02 9.05111687e-01 5.84313704e-01]] [0.45598936 0.2403831  0.35442981 0.54563453]




2. **Feature Selection**: In statistical modeling, reshaping may help in organizing features and observations in a way that makes feature selection processes more efficient.

   **Example**:
   

In [ ]:
# Organizing data for feature selection
data = np.random.rand(100, 10)  # 100 observations, 10 features
reshaped_data = data.reshape(100, 5, 2)  # Grouping features for analysis



3. **Time-Series Analysis**: Reshaping is particularly important in time-series data, where the sequence of data points is crucial. Reshaping can convert flat data into a time-series format.

   **Example**:
   

In [ ]:
# Reshaping data for time-series analysis
time_series_data = np.random.rand(365)  # Daily data for a year
reshaped_for_analysis = time_series_data.reshape(52, 7)  # Weekly data, 7 days a week