In [6]:
import numpy as np

In [39]:
array = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
array_1d = np.array(array)
print('array', array_1d)

array [0 1 2 3 4 5 6 7 8 9]


In [41]:
original_list = [3.14, 2.17, 0, 1, 2]

numpy_array = np.array(original_list)

int_array = numpy_array.astype(int)

print("Original List:", original_list)
print("NumPy Array:", numpy_array)
print("Integer Array:", int_array)

Original List: [3.14, 2.17, 0, 1, 2]
NumPy Array: [3.14 2.17 0.   1.   2.  ]
Integer Array: [3 2 0 1 2]


In [42]:
numpy_3x3_array = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(numpy_3x3_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [43]:
random_array = np.random.rand(4, 5)
array_2d = np.round(random_array, 2)

print(array_2d)

[[0.01 0.76 0.55 0.97 0.15]
 [0.35 0.28 0.05 0.74 0.87]
 [0.38 0.08 0.96 0.36 0.03]
 [0.82 0.47 0.79 0.01 0.93]]


In [44]:
second_row = array_2d[1, :]
print(second_row)

[0.35 0.28 0.05 0.74 0.87]


In [45]:
reversed = array[::1]
print(reversed)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [46]:
numpy_4x4_array = np.array([[1,0,0,0], [0,1,0,0], [0,0,1,0], [0,0,0,1]])
print(numpy_4x4_array)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [47]:
print("Sum:", np.sum(array))
print("Mean:", np.mean(array))

Sum: 45
Mean: 4.5


In [48]:
array_2 = np.arange(1, 21).reshape((4,5))
print(array_2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [49]:
odd_num = array_1d[array_1d % 2 != 0]
print(odd_num)

[1 3 5 7 9]
